### ISSUE TITLE
Got Error While Using Proxychains or Graftcp to Force Proxy on Tunasync

### ISSUE THREAD

**Issue by sparkcyf** [tuna/tunasync#96]
Version of tunasync: 0.3.3
(the return of graftcp and proxychains were same.)
While running the worker, (```proxychains tunasync worker --config xxx.conf >> xxx.log &``` or ```graftcp tunasync worker --config xxx.conf```) it returns:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9e464e]

goroutine 1 [running]:
github.com/tuna/tunasync/worker.newMirrorProvider(0xc42022c250, 0x7, 0x0, 0xc42001d890, 0x27, 0x5a0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/tuna/tunasync/worker/provider.go:137 +0x154e
github.com/tuna/tunasync/worker.(*Worker).initJobs(0xc4201c0f50)
        /home/travis/gopath/src/github.com/tuna/tunasync/worker/worker.go:158 +0xe1
github.com/tuna/tunasync/worker.GetTUNASyncWorker(0xc420001ba0, 0x36)
        /home/travis/gopath/src/github.com/tuna/tunasync/worker/worker.go:58 +0x30c
main.startWorker(0xc420212580, 0x0, 0x0)
        /home/travis/gopath/src/github.com/tuna/tunasync/cmd/tunasync/tunasync.go:63 +0x181
        /home/travis/gopath/src/github.com/tuna/tunasync/src/gopkg.in/urfave/cli.v1/app.go:490 +0xd4
gopkg.in/urfave/cli%2ev1.Command.Run(0xb689f1, 0x6, 0x0, 0x0, 0xc420015680, 0x1, 0x1, 0xb756ee, 0x19, 0x0, ...)
        /home/travis/gopath/src/github.com/tuna/tunasync/src/gopkg.in/urfave/cli.v1/command.go:210 +0xb6e
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420001860, 0xc420074100, 0x4, 0x4, 0x0, 0x0)
        /home/travis/gopath/src/github.com/tuna/tunasync/src/gopkg.in/urfave/cli.v1/app.go:255 +0x76f
main.main()
        /home/travis/gopath/src/github.com/tuna/tunasync/cmd/tunasync/tunasync.go:227 +0xdd5
```
There are similar issues here.
[https://stackoverflow.com/questions/16280176/go-panic-runtime-error-invalid-memory-address-or-nil-pointer-dereference](Stackoverflow)

**Comment by z4yx** [comment]
Fixed in the latest release. Thanks for your findings.
